"""empty message

Revision ID: 25afb1d13b14
Revises: 2807edd385a2
Create Date: 2021-12-23 14:56:01.377897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25afb1d13b14'
down_revision = '2807edd385a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('recipe',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=True),
    sa.Column('ingredients', sa.String(length=120), nullable=True),
    sa.Column('instructions', sa.String(length=120), nullable=True),
    sa.Column('comments', sa.String(length=120), nullable=True),
    sa.Column('classification', sa.String(length=120), nullable=True),
    sa.Column('ocassion', sa.String(length=120), nullable=True),
    sa.Column('difficulty', sa.String(length=120), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user', sa.Column('full_name', sa.String(length=120), nullable=False))
    op.drop_column('user', 'is_active')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.drop_column('user', 'full_name')
    op.drop_table('recipe')
    # ### end Alembic commands ###
