"""empty message

Revision ID: 3f26a044f3ca
Revises: e449b0d3f131
Create Date: 2022-01-02 17:25:23.152086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f26a044f3ca'
down_revision = 'e449b0d3f131'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('img',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=120), nullable=True),
    sa.Column('ingredients', sa.String(length=120), nullable=True),
    sa.Column('instructions', sa.String(length=120), nullable=True),
    sa.Column('ocassion', sa.String(length=120), nullable=True),
    sa.Column('difficulty', sa.String(length=120), nullable=True),
    sa.Column('comments', sa.String(length=120), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('image', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['image'], ['recipe.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_foreign_key(None, 'recipe', 'recipe', ['image'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'recipe', type_='foreignkey')
    op.drop_table('img')
    # ### end Alembic commands ###
