"""empty message

Revision ID: e449b0d3f131
Revises: cd732eeeee66
Create Date: 2021-12-31 22:43:41.485722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e449b0d3f131'
down_revision = 'cd732eeeee66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('recipe', sa.Column('image', sa.String(length=120), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recipe', 'image')
    # ### end Alembic commands ###
